# Supabase CLI Project Configuration
project_id = "skillprobe-backend"

[api]
port = 54321
extra_search_path = ["public", "extensions"]

[edge_runtime]
enabled = true
port = 54323

[functions.calculate-score]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false
